add_test([=[Grammar.Bootstrap]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Grammar.Bootstrap]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Grammar.Bootstrap]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Grammar.Form]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Grammar.Form]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Grammar.Form]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Lexicon.Simple]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Lexicon.Simple]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Lexicon.Simple]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Lexicon.Complex]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Lexicon.Complex]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Lexicon.Complex]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Parser.Simple]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Parser.Simple]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Parser.Simple]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Parser.Importing]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Parser.Importing]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Parser.Importing]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Regex.Compile]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Regex.Compile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Regex.Compile]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Regex.Match]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Regex.Match]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Regex.Match]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Skeleton.Deduce]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Skeleton.Deduce]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Skeleton.Deduce]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Syntactic.Simple]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Syntactic.Simple]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Syntactic.Simple]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Syntactic.ReduceShift]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Syntactic.ReduceShift]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Syntactic.ReduceShift]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Generic.Ambiguous]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Generic.Ambiguous]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Generic.Ambiguous]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Storage.Json]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Storage.Json]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Storage.Json]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Variable.Eval]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Variable.Eval]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Variable.Eval]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Template.Expressions]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Template.Expressions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Template.Expressions]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Template.Branch]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Template.Branch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Template.Branch]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Template.Iter]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Template.Iter]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Template.Iter]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Template.Extends]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Template.Extends]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Template.Extends]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Template.Call]=]  /home/runner/work/alioth/alioth/_codeql_build_dir/test/alioth-test [==[--gtest_filter=Template.Call]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Template.Call]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/alioth/alioth/_codeql_build_dir/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  alioth-test_TESTS Grammar.Bootstrap Grammar.Form Lexicon.Simple Lexicon.Complex Parser.Simple Parser.Importing Regex.Compile Regex.Match Skeleton.Deduce Syntactic.Simple Syntactic.ReduceShift Generic.Ambiguous Storage.Json Variable.Eval Template.Expressions Template.Branch Template.Iter Template.Extends Template.Call)
